version: '3'

services:
  web-php:
    build: .
    image: php-apache-ssmtp
    container_name: ${CONTAINER_NAME}
    ports:
      - "${HTTP_PORT}:80"
    restart:
      always
    volumes:
      - ./conf/ssmtp.conf:/etc/ssmtp/ssmtp.conf
      - ./web:/var/www/html
